Added Docker support
bddicken/languages pull request #12
Opened 2024-11-21 23:38 UTC by danmigdev

2024-11-26 09:00 UTC, seahindeniz requested changes

2024-11-26 10:04 UTC, danmigdev commented on README.md
> +  Benchmark[loops] C = 1.24
Didn't get the statement about merging results. Benchmark array contains the result of all the benchmarks (loops, fibonacci, etc) ran in docker. My intent is to test ALL the benchmark using Docker, not directly by underlying OS. I think the goal of the project is to highlight differences between languages, not to get the actual figures from your OS. As long as differences between results on Docker and OS are linear there are no concerns about using Docker to simplify dev end deployment. The question is: as per your experience, given a standing (from faster to slower) after the execution of the benchmarks on OS, could it be a totally different standing if ran on Docker?

2024-11-26 10:04 UTC, danmigdev commented on Dockerfile
> +RUN apt-get update && apt-get install -y \
Totally right!

2024-11-26 14:47 UTC, MikaelFangel commented
Fixes #52

2024-11-26 15:28 UTC, seahindeniz commented on README.md
> +  Benchmark[loops] C = 1.24
From that aspect I agree, results shouldn't come directly from the personal OS. However, I do believe that the docker virtualization isn't great as we expected and from my experience, it isn't constant across different devices and OS's.

My suggestion was putting outputs from each environment in different groups.
But to agree that the outputs must show "actual" figures, I'd consider choosing a place where it won't affected by anything related to a local environment, controlled under single organization/environment, in order to generate unaffected outputs such as running in a GitHub Actions runner

2024-11-26 15:31 UTC, seahindeniz commented on README.md
> +  Benchmark[loops] C = 1.24
What I'm also trying to say, a person could use the Dockerfile to test it from their local environment but the actual data that's documented should come from a unique, generally confirmed and observed environment

2024-11-26 15:34 UTC, seahindeniz commented on Dockerfile
> +    nodejs \
I think the nodejs in Ubuntu repository wasn't the official way of installation. I'm suspecting if it is the official channel 🫨

2024-11-27 06:17 UTC, rsb-23 commented on Dockerfile
> +RUN apt-get update && apt-get install -y \
So it will be latest stable version as of Dec 2024?

2024-11-29 21:05 UTC, MuriloChianfa commented
What do you guys think about change to apt instead of old apt-get?

2024-11-29 21:13 UTC, danmigdev commented
> What do you guys think about change to apt instead of old apt-get?

Sure!

2025-01-10 23:04 UTC, closed without merging

2025-01-10 23:04 UTC, bddicken commented
I still think docker support would be awesome, but the project has evolved quite a bit since this PR. lots of new languages, new programs, etc. Though I greatly appreciate the effort, I'm going to close this out so we can clean up old issues. If anyone here wants to re-tacke this in it's new state feel free.